// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kfdfbkchglfygyukstip.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmZGZia2NoZ2xmeWd5dWtzdGlwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMDM2NzQsImV4cCI6MjA2MTY3OTY3NH0.Mgl2irP4ntNJgsiuAy06L47g-rRpKzx92BYb6Uaywhk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});